### ISSUE TITLE
JQUERY: search box

### ISSUE THREAD

**Issue by arerickson28** [arerickson28/web-dev-project1#4]
Validate user input by suggests and spell check. See boot camp jQuery activities for ref.

**Comment by maayazed** [comment]
Ref 
`document.getElementById("searchButton").addEventListener("click", function() {
    let inputEl = document.getElementById("searchInput") ;
    console.log(inputEl.value)
    let searchInput = inputEl.value

    console.log(searchInput) ;

    let requestTickers1 = `https://api.polygon.io/v2/reference/tickers?sort=ticker&search=${searchInput}&perpage=50&page=1&apiKey=kYxMgr9oqrEq239cvWobO1J4q6rbXL6S`

    console.log(requestTickers1)

    getTickers(requestTickers1);
})` 

Input for the search listens to request tickers. Contributed by Rhyce. Issue has been resolved.
