### ISSUE TITLE
JAVASCRIPT: retrieval 

### ISSUE THREAD

**Issue by arerickson28** [arerickson28/web-dev-project1#7]
Use user search input to customize API URL.

**Comment by maayazed** [comment]
Ref
`for (let i=0; i< companies.length; i++) {
                    let newOption = document.createElement("button") ;

                    let ticker = companies[i]["ticker"] ;
    
                    let name = companies[i]["name"] ;

                    newOption.textContent = `(${ticker}) ${name}`

                    newOption.setAttribute("class", "clarifyChoice") ;

                    newOption.setAttribute("value", ticker)

                    newOption.addEventListener("click", function() {

                        while (companyOptions.firstChild) {
                            companyOptions.removeChild(companyOptions.firstChild);
                        } ;

                        console.log("calling addSearchToHistory")
                        addSearchToHistory(newOption.textContent, ticker) ;

                        while (recentSearches.firstChild) {
                            recentSearches.removeChild(recentSearches.firstChild);
                        } ;
                        
                        console.log("calling populateRecentSearches")
                        populateRecentSearches() ;

                        console.log("calling getStockData")
                        getStockData(ticker) ;

                    })

                    companyOptions.appendChild(newOption) ;

                }
            });   
}`
Contributed by Rhyce. Issue has been resolved.
